name: Update Activity Graph

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: ${{ github.repository_owner }}
          options: radius=16&theme=github-light&area=true
          output_path: assets/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit activity-graph
        run: |
          git config --global user.name "github-actions" # alternatively: github-actions[bot]
          git config --global user.email "github-actions@users.noreply.github.com"
          git add assets/*.svg
          git commit -m "Update README activity-graph"
          git push
